import { Injectable } from '@angular/core';
import { CountriesData } from 'countries-map';

@Injectable()

export class MapServices{

    getMapData(){
        let data: CountriesData = {
            'AH':{'value': '1'},
            'AF':{'value': '2'},
            'AK':{'value': '3'},
            'AL':{'value': '4'},
            'AR':{'value': '5'},
            'AM':{'value': '6'},
            'AY':{'value': '7'},
            'AB':{'value': '8'},
            'AZ':{'value': '9'},
            'BY':{'value': '10'},
            'BI':{'value': '11'},
            'BA':{'value': '12'},
            'BE':{'value': '13'},
            'BH':{'value': '14'},
            'BO':{'value': '15'},
            'BN':{'value': '16'},
            'BR':{'value': '17'},
            'BU':{'value': '18'},
            'CM':{'value': '19'},
            'CH':{'value': '20'},
            'CU':{'value': '21'},
            'DK':{'value': '22'},
            'EL':{'value': '23'},
            'EV':{'value': '24'},
            'GE':{'value': '25'},
            'HA':{'value': '26'},
            'HE':{'value': '27'},
            'HI':{'value': '28'},
            'HT':{'value': '29'},
            'IN':{'value': '30'},
            'ID':{'value': '31'},
            'IR':{'value': '32'},
            'IQ':{'value': '33'},
            'IS':{'value': '34'},
            'IT':{'value': '35'},
            'JA':{'value': '36'},
            'JW':{'value': '37'},
            'JO':{'value': '38'},
            'KA':{'value': '39'},
            'KZ':{'value': '40'},
            'KT':{'value': '41'},
            'KR':{'value': '42'},
            'KU':{'value': '43'},
            'KY':{'value': '44'},
            'LA':{'value': '45'},
            'LE':{'value': '46'},
            'MA':{'value': '47'},
            'MS':{'value': '48'},
            'ME':{'value': '49'},
            'MY':{'value': '50'},
            'MO':{'value': '51'},
            'MG':{'value': '52'},
            'MM':{'value': '53'},
            'NA':{'value': '54'},
            'NG':{'value': '55'},
            'NE':{'value': '56'},
            'NS':{'value': '57'},
            'OM':{'value': '58'},
            'OS':{'value': '59'},
            'PK':{'value': '60'},
            'PE':{'value': '61'},
            'PH':{'value': '62'},
            'PO':{'value': '63'},
            'QA':{'value': '64'},
            'RK':{'value': '65'},
            'ML':{'value': '66'},
            'SA':{'value': '67'},
            'SB':{'value': '68'},
            'SC':{'value': '69'},
            'SE':{'value': '70'},
            'SI':{'value': '71'},
            'SR':{'value': '72'},
            'SU':{'value': '73'},
            'SY':{'value': '74'},
            'TW':{'value': '75'},
            'TJ':{'value': '76'},
            'TS':{'value': '77'},
            'TM':{'value': '78'},
            'TH':{'value': '79'},
            'TB':{'value': '80'},
            'TL':{'value': '81'},
            'TN':{'value': '82'},
            'TU':{'value': '83'},
            'TK':{'value': '84'},
            'TV':{'value': '85'},
            'UL':{'value': '86'},
            'UA':{'value': '87'},
            'UR':{'value': '89'},
            'UZ':{'value': '90'},
            'VT':{'value': '91'},
            'YK':{'value': '92'},
            'YE':{'value': '93'},
          };

          return data;
    }
}